version: "3.7"

services:
  sw.asset.api:
    image: ${REGISTRY:-sw}/sw.asset.api:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "6300:5300"
    container_name: sw-asset
    build:
      context: ../../
      dockerfile: ./asset/api/sw.asset.api/Dockerfile